name: Copyright Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  copyright-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Java file copyright header
        run: |
          echo "🔍 Checking for correct copyright header..."

          failed=0

          while IFS= read -r -d '' file; do
            if ! grep -Fq '/*' "$file" || \
               ! grep -Fq ' * Copyright (c) 2025 mercury contributors' "$file" || \
               ! grep -Fq ' * This program is made available under the terms of the Apache License.' "$file" || \
               ! grep -Fq ' */' "$file"; then
              echo "❌ Missing copyright header in: $file"
              failed=1
            fi
          done < <(find core/src -name "*.java" -print0)

          if [ "$failed" -eq 1 ]; then
            exit 1
          fi

          echo "✅ All Java files contain the correct header."
